/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team.project;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
@Override
    public void start(Stage primaryStage) throws Exception {
        HomeScreen root = new HomeScreen();
        primaryStage.setTitle("PantryPal");
        primaryStage.setScene(new Scene(root, 500, 500));
        primaryStage.setResizable(false);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);}
}
